### ISSUE TITLE
Renaming the repo

### ISSUE THREAD

**Issue by slifty** [tvkitchen/tv-kitchen-website#10]
I'm not sure we want to do this, but we've moved away from prefixing everything with tv-kitchen.

Should we just have this repo be called `website` instead of `tv-kitchen-website`

**Comment by reefdog** [comment]
I'm cool with that.

**Comment by slifty** [comment]
@reefdog is it just a matter of renaming or do I need to update CNAME records somewhere... who set that up it was probably me.

I'll take this on tomorrow!

**Comment by slifty** [comment]
No DNS updates needed (forgot the custom URL is specified github side).

Repo name is updated; don't forget to fix your .git/config to reflect the new origin!
