### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by slifty** [tvkitchen/tv-kitchen-website#34]
#### Description
Is there any form of ethical (i.e. not google) analytics we might use?  would be great to know who is viewing what pages.

#### Relevant Resources / Research
None yet.

**Comment by piotrfonte** [comment]
Yes, I know a couple. I used [Plausible](https://plausible.io/) and it was perfectly fine for just general stats. The site I used it on was of an NGO—they reached out to Plausible support and got it for free in exchange for linking back. There’s also [Fathom](https://usefathom.com/) but I haven’t used it.

**Comment by slifty** [comment]
Plausible sounds perfect; I'm going to set up a free trial now and we should integrate it!
