### ISSUE TITLE
Tables in documentation

### ISSUE THREAD

**Issue by slifty** [tvkitchen/tv-kitchen-website#35]
#### Description
I'd love to make a few tables, but am not sure if there are associated styles for them.

For instance, I would like a table of data types:

- Value
- Description

And a directory of recipes:

- Name
- Outputs
- Description

**Comment by piotrfonte** [comment]
I assume these tables would be created inside docs’ markdown files with the following or similar syntax:

```
| foo | bar |
| :-- | :-: |
| baz | qux |
```

I’ll add these styles. No worries.

**Comment by piotrfonte** [comment]
Done in 4e5dc0fcf33e97858e627fee919274ebfeb1ea54
