### ISSUE TITLE
Set up continuous deployment

### ISSUE THREAD

**Issue by slifty** [tvkitchen/tv-kitchen-website#39]
#### Description
We use travis, gatsby, and github pages -- lets set up travis so commits to the main / master branch automatically trigger publication to gh-pages!

#### Relevant Resources / Research
- https://snyk.io/blog/deploying-a-gatsby-site-to-github-pages-from-travis-ci/

**Comment by chriszs** [comment]
It's what our .com does, can we just steal the Travis config for that?

Also: Netlify has some cool capabilities (branch preview in particular) and GitHub Actions is exceedingly good. We might want to consider alternatives in the future.
