### ISSUE TITLE
Code block padding at the end of a file

### ISSUE THREAD

**Issue by slifty** [tvkitchen/tv-kitchen-website#45]
#### Current Behavior
When I have a code block at the end of a file, the padding is a little off.

#### Input
<img width="1063" alt="image" src="https://user-images.githubusercontent.com/208884/93932599-7430e980-fcee-11ea-889a-9f10cbca9f36.png">

renders as

<img width="1063" alt="image" src="https://user-images.githubusercontent.com/208884/93932653-86128c80-fcee-11ea-8e06-a9f73529b65f.png">

#### Expected Behavior

I would expect it to render as:

<img width="1063" alt="image" src="https://user-images.githubusercontent.com/208884/93932722-9dea1080-fcee-11ea-9ee9-d54a92dae3f3.png">

#### Possible Solutions

I don't know the code solution, but just a note that it works if I put ANY content after the block.  For instance:

<img width="1063" alt="image" src="https://user-images.githubusercontent.com/208884/93932776-b0fce080-fcee-11ea-88c3-b11a2f9fcb6b.png">

**Comment by piotrfonte** [comment]
Fixed in 399594f4f1f4a9fbfe76296b9e637208ba3b6463
