### ISSUE TITLE
Font size for lists is small

### ISSUE THREAD

**Issue by slifty** [tvkitchen/tv-kitchen-website#46]
#### Current Behavior
Not sure if this is intentional (fine if so!) but numbered lists in recipes shows a smaller font than the rest of the text:

<img width="402" alt="image" src="https://user-images.githubusercontent.com/208884/93933207-50ba6e80-fcef-11ea-86f5-a9d619789652.png">

#### Input

```
1. [ccextractor](https://www.ccextractor.org/)
2. [ffmpeg](https://ffmpeg.org/)
3. A [running kafka instance](running-kafka).
```

#### Expected Behavior
Same size font (assuming that's the intent)

**Comment by piotrfonte** [comment]
Seems to me both are using correct font size, could you please double check?

<img width="309" alt="Screenshot 2020-10-11 at 13 31 32" src="https://user-images.githubusercontent.com/377206/95677487-252bf500-0bc6-11eb-8a20-d70e9dea44fa.png">

**Comment by slifty** [comment]
This is looking fine now; idk what was up.
