### ISSUE TITLE
Help page missing links

### ISSUE THREAD

**Issue by erekalper** [tvkitchen/tv-kitchen-website#49]
#### Current Behavior
The `VIEW ON GITHUB` and `READ THE DOCS` red buttons on the [help page](https://tv.kitchen/help/) don't have links associated with them.

#### Expected Behavior
Those buttons to have links.

#### Possible Solutions
Add links to the buttons.

**Comment by slifty** [comment]
In a sense the bug is that any of the other links work at all.

**Comment by erekalper** [comment]
The real bug was the links we made along the way.

**Comment by slifty** [comment]
I've issued a fix, but I'm not sure that the link to docs is optimal (is there another kind of link to use to prevent a full page refresh @piotrf ?)

**Comment by piotrfonte** [comment]
Yes, there’s Gatsby Link component, and I’ve just pushed it: 1570857d02bd7b7ecfaf075b0a1745629263c397

**Comment by slifty** [comment]
Awesome!  I'll close this out then.
