### ISSUE TITLE
Favicon in dark mode

### ISSUE THREAD

**Issue by slifty** [tvkitchen/tv-kitchen-website#53]
#### Description
I honestly don't know if there's a solution here (and plenty of major sites don't solve it...)

but I was wondering if we could make our favicon work well in dark mode!

Right now the pot is lost, though the colors aren't.

<img width="73" alt="image" src="https://user-images.githubusercontent.com/208884/94304916-5ce83b00-ff3e-11ea-8867-6f92c7db5a1e.png">

(Can favicons change depending on light / dark mode?)

#### Relevant Resources / Research
Looks like there are javascript based solutions: https://shubhamjain.co/til/dark-mode-favicon/

**Comment by piotrfonte** [comment]
Sure, we can detect dark mode and flip some colors.

**Comment by chriszs** [comment]
Over here on Chrome it's still pretty good:
<img width="33" alt="Screen Shot 2020-09-28 at 7 46 20 PM" src="https://user-images.githubusercontent.com/1103467/94496764-4acafe80-01c3-11eb-9c8a-f3ae9eedfd5b.png">

**Comment by piotrfonte** [comment]
Done in d43cb7fd5cd738316bfe12fbf8e6a07de657bd7e

<img width="88" alt="Screenshot 2020-10-11 at 14 29 58" src="https://user-images.githubusercontent.com/377206/95678653-409afe00-0bce-11eb-98f6-d2fcf93a674c.png">
