### ISSUE TITLE
Add bios to static landing page

### ISSUE THREAD

**Issue by reefdog** [tvkitchen/tv-kitchen-website#7]
Collect personal bios for primary contributors and add them to the static landing page.

- [x] Dan
- [x] Nancy
- [x] Chris
- [x] Justin
- [x] Add them and deployyy

**Comment by reefdog** [comment]
Justin:

> Justin built things with BIFFUD for the Duke Reporters’ Lab like [Talking Point Tracker](https://github.com/BadIdeaFactory/talking-point-tracker) and [Tech &amp; Check Alerts](https://github.com/TechAndCheck/tech-and-check-alerts). He previously worked on [DocumentCloud](https://www.documentcloud.org) and hides from social media at [justinreese.com](https://www.justinreese.com).

Chris (from his BIFFUD bio, as directed):

> Chris coaches a small team of computational journalists who analyze data, write code and do original design as the data editor at an investigative nonprofit. His work there has won Loeb, Meyer and Society for News Design awards. He designed and developed Emmy-nominated “Fatal Extraction” and contributed graphics to Pulitzer-winning “Breathless and Burdened.” He was formerly a reporting fellow at the Sunlight Foundation.

**Comment by nwatzmanco** [comment]
Nancy Watzman is director of Lynx LLC, based in Denver, Colorado.  She is a strategist specializing in developing and managing collaborations and partnerships to support journalists, technologists, and researchers in countering online dis- and mis-information, conducting investigations, and increasing newsroom sustainability.  Her current clients include [First Draft News](https://firstdraftnews.org/) and D[emocracy Fund ](https://democracyfund.org/
![Headshot2018](https://user-images.githubusercontent.com/11841729/87459399-94467d00-c5c8-11ea-88cc-49c16bed002f.jpg)
).

**Comment by nwatzmanco** [comment]
oh bleh that's so big. bleh.
