### ISSUE TITLE
Should content be in a subfolder?

### ISSUE THREAD

**Issue by slifty** [tvkitchen/tv-kitchen-website#9]
We're using github pages, I don't know how those work.

Should / can the actual page content exist in a subdirectory? That way our root can have things like `README` and `.github` and `LICENSE` without that being a part of our published site (which nobody will ever care about, but feels dirty)

**Comment by reefdog** [comment]
Bah, didn't even think about this. Hey cool our [LICENSE](https://tv.kitchen/LICENSE).

Looks like the only sub-directory option would be `/docs`, which is a little rigid:

![Screen Shot 2020-06-08 at 6 19 00 PM](https://user-images.githubusercontent.com/4731/84089436-965b6180-a9b4-11ea-932c-eb9fefb448eb.png)

But yeah, I suppose we should!

**Comment by slifty** [comment]
@pio I think this issue is obsolete now, yes?

**Comment by piotrfonte** [comment]
Yes!
